default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: railway_development
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] %>
  port: 5432

test:
  <<: *default
  database: rails_backend_app_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  